(cl:in-package autoware_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          ID-VAL
          ID
          LABEL-VAL
          LABEL
          SCORE-VAL
          SCORE
          COLOR-VAL
          COLOR
          VALID-VAL
          VALID
          SPACE_FRAME-VAL
          SPACE_FRAME
          POSE-VAL
          POSE
          DIMENSIONS-VAL
          DIMENSIONS
          VARIANCE-VAL
          VARIANCE
          VELOCITY-VAL
          VELOCITY
          ACCELERATION-VAL
          ACCELERATION
          POINTCLOUD-VAL
          POINTCLOUD
          CONVEX_HULL-VAL
          CONVEX_HULL
          POSE_RELIABLE-VAL
          POSE_RELIABLE
          VELOCITY_RELIABLE-VAL
          VELOCITY_RELIABLE
          ACCELERATION_RELIABLE-VAL
          ACCELERATION_RELIABLE
          INDICATOR_STATE-VAL
          INDICATOR_STATE
          BEHAVIOR_STATE-VAL
          BEHAVIOR_STATE
          USER_DEFINED_INFO-VAL
          USER_DEFINED_INFO
))